on: [push]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - name: Checkout repository code for the workflow run.
        uses: actions/checkout@v3

      - name: Publish Logseq graph as a single-page application.
        uses: logseq/publish-spa@v0.2.0

      - name: Create a .nojekyll file in the www folder to bypass Jekyll processing.
        run: touch $GITHUB_WORKSPACE/www/.nojekyll

      - name:  Retrieves the folder name for public deployment and sets environment variables.
        run: |
          if [[ -n "${{ env.GITHUB_IO }}" ]]; then
            repo_name=${{ env.GITHUB_IO }}
          else
            repo_full_name="${{ github.repository }}"
            repo_name="${repo_full_name%%/*}"
          fi
          repo_name_lowercase=$(echo "$repo_name" | tr '[:upper:]' '[:lower:]')
          echo "REPO_REPO=${repo_name}/${repo_name_lowercase}.github.io" >> $GITHUB_ENV
          if [[ -n "${{ env.FOLDER }}" ]]; then
            echo "REPO_FOLDER=${{ env.FOLDER }}" >> $GITHUB_ENV
          else
            repo_folder="${repo_full_name#*/}"
            echo "REPO_FOLDER=${repo_folder}" >> $GITHUB_ENV
          fi


      - name: Deploys the Logseq graph to GitHub Pages.
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
          token: ${{ secrets.GH_TOKEN }}
          repository-name: ${{ env.REPO_REPO }}
          branch: main
          target-folder: ${{ env.REPO_FOLDER }}